ENH: handle unicode enc error in file_write()
One some (HPC) systems, we occasionally see random errors of the form

        UnicodeEncodeError: 'ascii' codec can't encode characters
        in position 4475-4476

when calling file_write() caused by run(..., capture_logs="file"). This may be
caused by oldish file systems that can't handle unicode files.